### ISSUE TITLE
Determine how different content pages will be created and displayed.

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#1]
Right now we only have an index.html. This should of course be the landing page, but how will we display the information from the other content pages, will these also be static (or mostly static) html pages, or will the data be loaded into a div of the index.html. 

This needs to be decided so that we can determine how to best deliver the pages, and what backend support they will need.

**Comment by WilliamReed2004** [comment]
We will be using a one-page layout
