### ISSUE TITLE
Find or Create a user icon in SVN to use when an instructor (member of the team) doesn't have an image

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#30]
We need to provide a default image in the event one has not been configured for the user via the backend. This is strictly design work, either find a nice one online that is allowed to be used, or draw one ourselves, but it really should be SVG so that we can reuse it in various fields.

**Comment by WilliamReed2004** [comment]
I can't upload .svg here, so this is .png, but would this be fine? It is a simple line with a transparent background (so it's usable almost everywhere)

![user_merged inkcape](https://user-images.githubusercontent.com/29880819/123664553-b962e880-d837-11eb-8640-69f266f2ff1f.png)
