### ISSUE TITLE
Build a simple contact form 

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#4]
Create a contact form in HTML. The form should be available in both German and English languages.
The form should contain the following fields:
* Mrs., Ms., Mr. (should be displayed as Radio buttons)
* First Name (text field)
* Last Name (text field)
* Email Address (text field)
* Street (text field)
* City  (text field)
* Postcode (text field)
* Telephone number (text field)
* Preference of communication (Email or Telephone as checkboxes)
* Comment field (text area)

The validation requirements would be 
1. If no first name is given then at least the Mrs. Ms. Mr. must be selected.
2. Email address must be provided if the Email checkbox is marked
3. Telephone number must be provided if Telephone checkbox is marked.
4. Comment field should have content.

**Comment by JRSofty** [comment]
@WilliamReed2004 my last commit makes the call from the JS to the backend (PHP). Please check that on success that when the form is removed, there is an information box to replace it that informs the user that the message was sent.

**Comment by WilliamReed2004** [comment]
Finished, also added Error Message
