### ISSUE TITLE
Create a themed 404 page.

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#6]
The page should contain the same textual formatting and colors as the main page and should provide a link to return to the main page. The page shall be named 404.html and resides next to the index.html. It will be called when someone attempts to browse the backend code files directly.

**Comment by JRSofty** [comment]
The 404 page is created but needs to be made pretty. That's where @WilliamReed2004 comes in.

**Comment by WilliamReed2004** [comment]
finished
