### ISSUE TITLE
Investigate the possibility to replace Fontawesome with Friconix

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#86]
Friconix has more options that we do not have to pay for and uses the `<i />` tag to put things in. Only the class called would have to be modified. 

We would have to see how it affects the site loading, as it is not able to be self-hosted. My experience to this point is that it is not adding unwanted handling in sites that use it.

**Comment by rosenclosed** [comment]
should be all changed and working in #111
