### ISSUE TITLE
Make the "Kurse" menu item have sub menu items for the different types

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#89]
There are different class types:
* [ ] Geburtsvorbereitung with kurzel 'gbv'
* [ ] Babypflege with kurzel 'bp'
* [ ] Rückbildungsgymnastik with kurzel 'rubi'
* [ ] Babytreff with kurzel 'bt'
* [ ] Erste Hilfe with kurzel 'eh'
* [ ] Yoga with kurzel 'yoga'
* [ ] Sonstige with kurzel 'other'

There are already divs with IDs for these classes, and should be used in the menu item.

**Comment by rosenclosed** [comment]
Need the hebamio api key to test this

**Comment by rosenclosed** [comment]
completed by #112
