### ISSUE TITLE
Correct handling of classes loading to prevent empty class sections being removed from the HTML

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#90]
Currently the javascript that places the classes into their different classes sections, will check if there are no classes for that section and remove it from the HTML. This will cause problems with the issue #89 which will need the sections even if they are empty.

Instead an "No classes for this type" should appear if there are no classes for the desired class type.

**Comment by rosenclosed** [comment]
Should be fixed with https://github.com/ReedFamily/hebamme-web/commit/116fb907fdb49451fe4970b19f602aabe9d981cb

@JRSofty need hebamio api access to test

**Comment by rosenclosed** [comment]
resolved by #114
