### ISSUE TITLE
Banners for "iebanner" announcment must have their own ID values

### ISSUE THREAD

**Issue by JRSofty** [ReedFamily/hebamme-web#96]
For every 
` <p id="iebanner" class="browsehappy iebanner">
        Sie verwenden einen <strong>veralteten</strong> Webbrowser. Bitte<a href="https://bestvpn.org/outdatedbrowser/de">
            aktualisieren Sie Ihren Browser</a> um diese Seite zu nutzen.
    </p>`

the `id` must be different. There are several instances of this paragraph tag in the index.html and they all use the same id, which is invalid HTML5. Please correct.

**Comment by rosenclosed** [comment]
fixed by #110
